# https://docs.determinate.systems/guides/automatically-fix-hashes-in-github-actions/
name: Nix Flake Update

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build
        id: build
        run: nix build
        continue-on-error: true

      - name: Fix hashes
        if: steps.build.outcome == 'failure' && github.event_name == 'push'
        run: determinate-nixd fix hashes --auto-apply

      - name: Open PR with hash fix
        if: steps.build.outcome == 'failure' && github.event_name == 'push'
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          commit-message: "nix: update vendorHash"
          title: "nix: update vendorHash"
          body: |
            Automated update of `vendorHash` in `flake.nix` after `nix build` failed on `main`.
          branch: nix/update-vendor-hash
          sign-commits: true
          delete-branch: true

      - name: Verify build
        if: steps.build.outcome == 'failure'
        run: nix build
